// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var Grid, directions, directionsIndexed, getArrowImage, getArrowImages, mouseMove;

  Grid = function(playfield, pathSet, canvas) {
    this.playfield = playfield;
    this.pathSet = pathSet;
    this.canvas = canvas;
    this.cellSize = 36;
    this.COLORS = {
      BACKGROUND: '#272822',
      PATHBACKGROUND: '#49483E',
      GRID: '#EDF',
      PATHINDICATOR: 'rgb(24, 155, 230)',
      FONT: '#EDF'
    };
    this.canvas.width = this.playfield.width * this.cellSize;
    this.canvas.height = this.playfield.height * this.cellSize;
    this.con2d = this.canvas.getContext('2d');
    this.con2d.textAlign = 'center';
    this.con2d.textBaseline = 'middle';
    this.con2d.font = '20px Consolas, monospace';
    this.con2d.strokeStyle = '#FFF';
    this.con2d.lineWidth = 0.8;
    this.onChange = null;
    this.mouseState = {
      x: -1,
      y: -1
    };
    this._setupMouseListener();
    this.hitRegions = [];
    this._setupHitRegions();
    this.arrowImages = getArrowImages(this.cellSize / 3, this.COLORS);
    this.draw();
  };

  getArrowImage = function(size, angle, COLORS) {
    var canvas, con2d;
    canvas = document.createElement('canvas');
    canvas.width = size;
    canvas.height = size;
    con2d = canvas.getContext('2d');
    con2d.strokeStyle = COLORS.PATHINDICATOR;
    con2d.lineWidth = 2;
    con2d.translate(size / 2, size / 2);
    con2d.rotate(angle);
    con2d.beginPath();
    con2d.moveTo(-size / 2 - 1, size / 2 - 4);
    con2d.lineTo(0, -size / 2 + 3);
    con2d.lineTo(size / 2 + 1, size / 2 - 4);
    con2d.stroke();
    return canvas;
  };

  getArrowImages = function(size, COLORS) {
    return {
      '^': getArrowImage(size, 0, COLORS),
      '<': getArrowImage(size, -Math.PI / 2, COLORS),
      'v': getArrowImage(size, Math.PI, COLORS),
      '>': getArrowImage(size, Math.PI / 2, COLORS)
    };
  };

  directions = [
    {
      char: '<',
      offset: {
        x: 0,
        y: 1
      }
    }, {
      char: '^',
      offset: {
        x: 1,
        y: 0
      }
    }, {
      char: 'v',
      offset: {
        x: 1,
        y: 2
      }
    }, {
      char: '>',
      offset: {
        x: 2,
        y: 1
      }
    }
  ];

  directionsIndexed = directions.reduce(function(ret, _arg) {
    var char, offset;
    char = _arg.char, offset = _arg.offset;
    ret.set(char, offset);
    return ret;
  }, new Map);

  Grid.prototype._setupHitRegions = function() {
    var char, dir, getCellRegion, i, j, offset, _i, _j, _k, _len, _ref, _ref1;
    getCellRegion = (function(x, y, offX, offY, dir) {
      return {
        x: x,
        y: y,
        dir: dir,
        start: {
          x: x * this.cellSize + this.cellSize / 3 * offX,
          y: y * this.cellSize + this.cellSize / 3 * offY
        },
        end: {
          x: x * this.cellSize + this.cellSize / 3 * (offX + 1),
          y: y * this.cellSize + this.cellSize / 3 * (offY + 1)
        },
        size: {
          width: this.cellSize / 3,
          height: this.cellSize / 3
        }
      };
    }).bind(this);
    for (i = _i = 0, _ref = this.playfield.width; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      for (j = _j = 0, _ref1 = this.playfield.height; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
        char = this.playfield.getAt(i, j);
        if ((char === '^' || char === '<' || char === 'v' || char === '>') && ((this.pathSet.getStartingFrom(i, j, '')) != null)) {
          offset = directionsIndexed.get(char);
          this.hitRegions.push(getCellRegion(i, j, offset.x, offset.y, char));
        } else {
          for (_k = 0, _len = directions.length; _k < _len; _k++) {
            dir = directions[_k];
            if ((this.pathSet.getStartingFrom(i, j, dir.char)) != null) {
              offset = dir.offset;
              this.hitRegions.push(getCellRegion(i, j, offset.x, offset.y, dir.char));
            }
          }
        }
      }
    }
  };

  Grid.prototype._getRegion = function(x, y) {
    var region, _i, _len, _ref;
    _ref = this.hitRegions;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      region = _ref[_i];
      if ((region.start.x <= x && x <= region.end.x) && (region.start.y <= y && y <= region.end.y)) {
        return region;
      }
    }
    return null;
  };

  mouseMove = function(e) {
    var newRegion, _ref, _ref1;
    this.mouseState.x = (_ref = e.offsetX) != null ? _ref : e.layerX;
    this.mouseState.y = (_ref1 = e.offsetY) != null ? _ref1 : e.layerY;
    newRegion = this._getRegion(this.mouseState.x, this.mouseState.y);
    if (newRegion !== this.currentRegion) {
      this.currentRegion = newRegion;
      if (this.currentRegion != null) {
        this.highlightedPath = this.pathSet.getStartingFrom(this.currentRegion.x, this.currentRegion.y, this.currentRegion.dir);
      } else {
        this.highlightedPath = null;
      }
      this.draw();
      return typeof this.onChange === "function" ? this.onChange(this.highlightedPath) : void 0;
    }
  };

  Grid.prototype._setupMouseListener = function() {
    this._mouseMove = mouseMove.bind(this);
    this.canvas.addEventListener('mousemove', this._mouseMove);
  };

  Grid.prototype.draw = function() {
    var hitRegion, i, j, _i, _j, _k, _l, _len, _m, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    this.con2d.fillStyle = this.COLORS.BACKGROUND;
    this.con2d.fillRect(0, 0, this.canvas.width, this.canvas.height);
    this.con2d.fillStyle = this.COLORS.PATHBACKGROUND;
    if ((_ref = this.highlightedPath) != null) {
      _ref.list.forEach((function(_this) {
        return function(entry) {
          return _this.con2d.fillRect(entry.x * _this.cellSize, entry.y * _this.cellSize, _this.cellSize, _this.cellSize);
        };
      })(this));
    }
    this.con2d.fillStyle = this.COLORS.FONT;
    for (i = _i = 0, _ref1 = this.playfield.width; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
      for (j = _j = 0, _ref2 = this.playfield.height; 0 <= _ref2 ? _j < _ref2 : _j > _ref2; j = 0 <= _ref2 ? ++_j : --_j) {
        this.con2d.fillText(this.playfield.getAt(i, j), i * this.cellSize + this.cellSize / 2, j * this.cellSize + this.cellSize / 2);
      }
      _ref3 = this.hitRegions;
      for (_k = 0, _len = _ref3.length; _k < _len; _k++) {
        hitRegion = _ref3[_k];
        this.con2d.drawImage(this.arrowImages[hitRegion.dir], hitRegion.start.x, hitRegion.start.y);
      }
    }
    this.con2d.strokeStyle = this.COLORS.GRID;
    this.con2d.beginPath();
    for (i = _l = 1, _ref4 = this.playfield.width; 1 <= _ref4 ? _l < _ref4 : _l > _ref4; i = 1 <= _ref4 ? ++_l : --_l) {
      this.con2d.moveTo(i * this.cellSize, 0);
      this.con2d.lineTo(i * this.cellSize, this.canvas.height);
    }
    for (i = _m = 1, _ref5 = this.playfield.height; 1 <= _ref5 ? _m < _ref5 : _m > _ref5; i = 1 <= _ref5 ? ++_m : --_m) {
      this.con2d.moveTo(0, i * this.cellSize);
      this.con2d.lineTo(this.canvas.width, i * this.cellSize);
    }
    this.con2d.stroke();
  };

  Grid.prototype.setListener = function(onChange) {
    this.onChange = onChange;
  };

  Grid.prototype.destroy = function() {
    return this.canvas.removeEventListener('mousemove', this._mouseMove);
  };

  if (window.viz == null) {
    window.viz = {};
  }

  window.viz.Grid = Grid;

}).call(this);
