// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var GraphCompiler, List, assemble, computeIndegree;

  List = bef.List;

  computeIndegree = function(nodes) {
    return (Object.keys(nodes)).reduce(function(indegree, nodeName) {
      nodes[nodeName].forEach(function(edge) {
        var to;
        to = edge.to;
        if (indegree.has(to)) {
          return indegree.set(to, (indegree.get(to)) + 1);
        } else {
          return indegree.set(to, 1);
        }
      });
      return indegree;
    }, new Map);
  };

  assemble = function(graph) {
    var cycledNodes, df, wrapIfLooping;
    cycledNodes = new Set;
    wrapIfLooping = function(stack, node, code) {
      if (cycledNodes.has(node)) {
        return "while (programState.isAlive()) _" + node + ": {\n	" + code + "\n}";
      } else {
        return code;
      }
    };
    df = function(node, stack) {
      var branch, branch0, branch1, branch2, branch3, edgeCode, neighbours, newStack, randomCode, selectCode;
      if (graph.nodes[node] == null) {
        return '';
      }
      if ((stack.find(node)) != null) {
        cycledNodes.add(node);
        return "break _" + node + ";";
      } else {
        neighbours = graph.nodes[node];
        newStack = stack.con(node);
        switch (neighbours.length) {
          case 4:
            branch0 = df(neighbours[0].to, newStack);
            branch1 = df(neighbours[1].to, newStack);
            branch2 = df(neighbours[2].to, newStack);
            branch3 = df(neighbours[3].to, newStack);
            randomCode = "var choice = programState.randInt(4);\nswitch (choice) {\n	case 0:\n		" + neighbours[0].code + "\n		" + branch0 + "\n		break;\n	case 1:\n		" + neighbours[1].code + "\n		" + branch1 + "\n		break;\n	case 2:\n		" + neighbours[2].code + "\n		" + branch2 + "\n		break;\n	case 3:\n		" + neighbours[3].code + "\n		" + branch3 + "\n		break;\n}";
            return wrapIfLooping(cycledNodes, node, randomCode);
          case 2:
            branch0 = df(neighbours[0].to, newStack);
            branch1 = df(neighbours[1].to, newStack);
            selectCode = "if (programState.pop()) {\n	" + neighbours[0].code + "\n	" + branch0 + "\n} else {\n	" + neighbours[1].code + "\n	" + branch1 + "\n}";
            return wrapIfLooping(cycledNodes, node, selectCode);
          case 1:
            branch = df(neighbours[0].to, newStack);
            edgeCode = "" + neighbours[0].code + "\n" + branch;
            return wrapIfLooping(cycledNodes, node, edgeCode);
          case 0:
            return 'return;';
        }
      }
    };
    return df(graph.start, List.EMPTY);
  };

  GraphCompiler = {
    assemble: assemble
  };

  if (window.bef == null) {
    window.bef = {};
  }

  window.bef.GraphCompiler = GraphCompiler;

}).call(this);
