// Generated by CoffeeScript 1.12.7
(function() {
  var code, input;

  code = '&v -1<\n>>::.|\n>    @';

  input = '9';

  if (window.befSample == null) {
    window.befSample = {};
  }

  window.befSample['count-down'] = {
    code: code,
    input: input
  };

}).call(this);
