// Generated by CoffeeScript 1.11.0
(function() {
  var code, input;

  code = '0v      +1<\n>>:.:99*\\`|\n>         @';

  input = '';

  if (window.befSample == null) {
    window.befSample = {};
  }

  window.befSample['count-up'] = {
    code: code,
    input: input
  };

}).call(this);
