// Generated by CoffeeScript 1.8.0
(function() {
  var code, input;

  code = '>>78*vD\nv$_#>vN\n7#!@  A\n3 :v??v\n9,-""""\n4+1ACGT\n+,,""""\n>^^<<<<';

  input = '';

  if (window.befSample == null) {
    window.befSample = {};
  }

  window.befSample['dna-code'] = {
    code: code,
    input: input
  };

}).call(this);
