// Generated by CoffeeScript 1.8.0
(function() {
  var code, input;

  code = '&>:1-:v v *_$.@\n ^    _$>\\:^';

  input = '5';

  if (window.befSample == null) {
    window.befSample = {};
  }

  window.befSample['factorial'] = {
    code: code,
    input: input
  };

}).call(this);
