// Generated by CoffeeScript 1.8.0
(function() {
  var code, input;

  code = '0"!dlroW" v\nv"Hello, "<\n>:#,_@';

  input = '';

  if (window.befSample == null) {
    window.befSample = {};
  }

  window.befSample['hello-world'] = {
    code: code,
    input: input
  };

}).call(this);
