// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var StackingCompiler, binaryOperator, codeMap, digitPusher, isNumber, makeStack;

  isNumber = function(obj) {
    return typeof obj === 'number';
  };

  digitPusher = function(digit) {
    return function(x, y, dir, index, stack) {
      stack.push(digit);
    };
  };

  binaryOperator = function(operatorFunction, operatorChar, stringFunction) {
    return function(x, y, dir, index, stack) {
      var fun, operand1, operand2;
      operand1 = stack.pop();
      operand2 = stack.pop();
      fun = (isNumber(operand1)) && (isNumber(operand2)) ? operatorFunction : stringFunction;
      stack.push(fun(operand1, operand2));
    };
  };

  codeMap = {
    ' ': function() {},
    '0': digitPusher(0),
    '1': digitPusher(1),
    '2': digitPusher(2),
    '3': digitPusher(3),
    '4': digitPusher(4),
    '5': digitPusher(5),
    '6': digitPusher(6),
    '7': digitPusher(7),
    '8': digitPusher(8),
    '9': digitPusher(9),
    '+': binaryOperator((function(o1, o2) {
      return o2 + o1;
    }), '+', function(o1, o2) {
      return "(" + o2 + " + " + o1 + ")";
    }),
    '-': binaryOperator((function(o1, o2) {
      return o2 - o1;
    }), '-', function(o1, o2) {
      return "(" + o2 + " - " + o1 + ")";
    }),
    '*': binaryOperator((function(o1, o2) {
      return o2 * o1;
    }), '*', function(o1, o2) {
      return "(" + o2 + " * " + o1 + ")";
    }),
    '/': binaryOperator((function(o1, o2) {
      return Math.floor(o2 / o1);
    }), '/', function(o1, o2) {
      return "Math.floor(" + o2 + " / " + o1 + ")";
    }),
    '%': binaryOperator((function(o1, o2) {
      return o2 % o1;
    }), '%', function(o1, o2) {
      return "(" + o2 + " % " + o1 + ")";
    }),
    '!': function(x, y, dir, index, stack) {
      stack.push("(+!" + (stack.pop()) + ")");
    },
    '`': binaryOperator((function(o1, o2) {
      return +(o1 < o2);
    }), '`', function(o1, o2) {
      return "(+(" + o1 + " < " + o2 + "))";
    }),
    '^': function() {},
    '<': function() {},
    'v': function() {},
    '>': function() {},
    '?': function() {},
    '_': function() {},
    '|': function() {},
    '"': function() {},
    ':': function(x, y, dir, index, stack) {
      var top;
      top = stack.peek();
      stack.push(top);
    },
    '\\': function(x, y, dir, index, stack) {
      var e1, e2;
      e1 = stack.pop();
      e2 = stack.pop();
      stack.push(e1, e2);
    },
    '$': function(x, y, dir, index, stack) {
      stack.pop();
    },
    '.': function(x, y, dir, index, stack) {
      stack.out("programState.out(" + (stack.pop()) + ")");
    },
    ',': function(x, y, dir, index, stack) {
      stack.out("programState.out(String.fromCharCode(" + (stack.pop()) + "))");
    },
    '#': function() {},
    'p': function(x, y, dir, index, stack, from, to) {
      var p1, p2, p3;
      p1 = stack.pop();
      p2 = stack.pop();
      p3 = stack.pop();
      stack.dump();
      stack.pushChunk("programState.put(\n	" + p1 + ",\n	" + p2 + ",\n	" + p3 + ",\n	" + x + ", " + y + ", '" + dir + "', " + index + ",\n	'" + from + "', '" + to + "'\n)\nif (programState.flags.pathInvalidatedAhead) {\n	return\n}");
    },
    'g': function(x, y, dir, index, stack) {
      stack.push("programState.get(" + (stack.pop()) + ", " + (stack.pop()) + ")");
    },
    '&': function(x, y, dir, index, stack) {
      stack.push(stack.next());
    },
    '~': function(x, y, dir, index, stack) {
      stack.push(stack.nextChar());
    },
    '@': function(x, y, dir, index, stack) {
      stack.exit();
    }
  };

  StackingCompiler = function() {};

  makeStack = function(uid) {
    var chunks, declarations, exitRequest, makeNext, reads, stack, stackObj, writes;
    stack = [];
    declarations = [];
    reads = [];
    writes = [];
    chunks = [];
    exitRequest = false;
    stackObj = {};
    stackObj.push = function() {
      Array.prototype.push.apply(stack, arguments);
    };
    stackObj.pop = function() {
      var name;
      if (stack.length > 0) {
        return stack.pop();
      } else {
        name = "p" + uid + "_" + declarations.length;
        declarations.push("var " + name + " = programState.pop()");
        return name;
      }
    };
    stackObj.peek = function() {
      var name;
      if (stack.length) {
        return stack[stack.length - 1];
      } else {
        name = "p" + uid + "_" + declarations.length;
        declarations.push("var " + name + " = programState.peek()");
        return name;
      }
    };
    makeNext = function(methodName) {
      return function() {
        var name;
        name = "r" + uid + "_" + reads.length;
        reads.push("var " + name + " = programState." + methodName + "()");
        return name;
      };
    };
    stackObj.next = makeNext('next');
    stackObj.nextChar = makeNext('nextChar');
    stackObj.out = function(entry) {
      writes.push(entry);
    };
    stackObj.dump = function() {
      chunks.push("" + (declarations.join('\n')) + "\n" + (reads.join('\n')) + "\n" + (stack.length > 0 ? "programState.push(" + (stack.join(', ')) + ")" : '') + "\n" + (writes.join('\n')));
      stack = [];
      declarations = [];
      reads = [];
      writes = [];
    };
    stackObj.pushChunk = function(entry) {
      chunks.push(entry);
    };
    stackObj.stringify = function() {
      return "" + (chunks.join('\n')) + "\n" + (exitRequest ? 'programState.exit()' : '');
    };
    stackObj.exit = function() {
      return exitRequest = true;
    };
    return stackObj;
  };

  StackingCompiler.assemble = function(path) {
    var charList, stack;
    charList = path.getAsList();
    stack = makeStack(path.id);
    charList.forEach(function(entry, i) {
      var codeGenerator;
      if (entry.string) {
        stack.push(entry.char.charCodeAt(0));
      } else {
        codeGenerator = codeMap[entry.char];
        if (codeGenerator != null) {
          codeGenerator(entry.x, entry.y, entry.dir, i, stack, path.from, path.to);
        }
      }
    });
    stack.dump();
    return stack.stringify();
  };

  StackingCompiler.compile = function(path) {
    var code, compiled;
    code = StackingCompiler.assemble(path);
    path.code = code;
    compiled = new Function('programState', code);
    return path.body = compiled;
  };

  if (window.bef == null) {
    window.bef = {};
  }

  window.bef.StackingCompiler = StackingCompiler;

}).call(this);
