// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var loadProgram, run, saveProgram, setupCompilers, setupEditors, setupRunButton, setupSamples, _ref;

  _ref = window.viz, setupEditors = _ref.setupEditors, setupSamples = _ref.setupSamples, setupCompilers = _ref.setupCompilers, setupRunButton = _ref.setupRunButton, saveProgram = _ref.saveProgram, loadProgram = _ref.loadProgram;

  run = function(editors, compiler) {
    var playfield, prettyJs, rawJs, runtime, stringedOutput, stringedStack;
    saveProgram(editors);
    playfield = new bef.Playfield();
    playfield.fromString(editors.source.getValue(), 16, 10);
    runtime = new bef.EagerRuntime();
    runtime.execute(playfield, {
      jumpLimit: 1000,
      compiler: compiler
    }, editors.input.getValue());
    rawJs = runtime.code;
    prettyJs = js_beautify(rawJs);
    editors.js.setValue(prettyJs, 1);
    stringedStack = runtime.programState.stack.join(' ');
    stringedOutput = runtime.programState.outRecord.join(' ');
    return editors.output.setValue("Stack: " + stringedStack + "\nOutput: " + stringedOutput, 1);
  };

  (function() {
    var compiler, editors;
    compiler = bef.BinaryCompiler;
    editors = setupEditors();
    setupSamples(window.befSample, editors);
    setupCompilers(function(_compiler) {
      compiler = _compiler;
      return run(editors, compiler);
    });
    setupRunButton(function() {
      return run(editors, compiler);
    });
    loadProgram(editors);
    return run(editors, compiler);
  })();

}).call(this);
