// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var compiler, inputEditor, jsEditor, outputEditor, run, setupCompilers, setupEditors, setupRunButton, setupSamples, sourceEditor;

  sourceEditor = null;

  inputEditor = null;

  outputEditor = null;

  jsEditor = null;

  compiler = bef.StackingCompiler;

  setupSamples = function() {
    var select;
    select = document.getElementById('sample');
    (Object.keys(window.befSample)).forEach(function(sampleName) {
      var option;
      option = document.createElement('option');
      option.textContent = sampleName;
      select.appendChild(option);
    });
    return select.addEventListener('change', function() {
      var code, input, _ref;
      _ref = window.befSample[this.value], input = _ref.input, code = _ref.code;
      sourceEditor.setValue(code, 1);
      inputEditor.setValue(input, 1);
    });
  };

  setupCompilers = function() {
    var select;
    select = document.getElementById('compiler');
    ['StackingCompiler', 'OptimizingCompiler', 'BasicCompiler'].forEach(function(sampleName) {
      var option;
      option = document.createElement('option');
      option.textContent = sampleName;
      select.appendChild(option);
    });
    return select.addEventListener('change', function() {
      compiler = bef[this.value];
      run();
    });
  };

  setupEditors = function() {
    sourceEditor = ace.edit('source-editor');
    sourceEditor.setTheme('ace/theme/monokai');
    sourceEditor.setFontSize(14);
    inputEditor = ace.edit('input-editor');
    inputEditor.setTheme('ace/theme/monokai');
    inputEditor.getSession().setUseWrapMode(true);
    inputEditor.setFontSize(14);
    outputEditor = ace.edit('output-editor');
    outputEditor.setTheme('ace/theme/monokai');
    outputEditor.getSession().setUseWrapMode(true);
    outputEditor.setReadOnly(true);
    outputEditor.setFontSize(14);
    jsEditor = ace.edit('js-editor');
    jsEditor.setTheme('ace/theme/monokai');
    jsEditor.getSession().setMode('ace/mode/javascript');
    jsEditor.getSession().setUseWrapMode(true);
    jsEditor.setReadOnly(true);
    return jsEditor.setFontSize(14);
  };

  run = function() {
    var playfield, prettyJs, rawJs, runtime, stringedOutput, stringedStack;
    playfield = new bef.Playfield();
    playfield.fromString(sourceEditor.getValue(), 16, 10);
    runtime = new bef.EagerRuntime();
    runtime.execute(playfield, {
      jumpLimit: 100,
      compiler: compiler
    }, inputEditor.getValue());
    rawJs = runtime.code;
    prettyJs = js_beautify(rawJs);
    jsEditor.setValue(prettyJs, 1);
    stringedStack = runtime.programState.stack.join(' ');
    stringedOutput = runtime.programState.outRecord.join(' ');
    return outputEditor.setValue("Stack: " + stringedStack + "\nOutput: " + stringedOutput, 1);
  };

  setupRunButton = function() {
    return (document.getElementById('run')).addEventListener('click', run);
  };

  setupSamples();

  setupCompilers();

  setupEditors();

  setupRunButton();

  run();

}).call(this);
