// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var OptimizinsCompiler, binaryOperator, codeMap, digitPusher, isNumber;

  isNumber = function(obj) {
    return typeof obj === 'number';
  };

  digitPusher = function(digit) {
    return function(x, y, dir, index, stack) {
      stack.push(digit);
      return "/* " + digit + " */";
    };
  };

  binaryOperator = function(operatorFunction, operatorChar, stringFunction) {
    return function(x, y, dir, index, stack) {
      var operand1, operand2;
      operand1 = stack.length ? stack.pop() : 'runtime.pop()';
      operand2 = stack.length ? stack.pop() : 'runtime.pop()';
      if ((isNumber(operand1)) && (isNumber(operand2))) {
        stack.push(operatorFunction(operand1, operand2));
        return "/* " + operatorChar + " */";
      } else {
        return "/* " + operatorChar + " */  runtime.push(" + (stringFunction(operand1, operand2)) + ")";
      }
    };
  };

  codeMap = {
    ' ': function() {
      return '/*   */';
    },
    '0': digitPusher(0),
    '1': digitPusher(1),
    '2': digitPusher(2),
    '3': digitPusher(3),
    '4': digitPusher(4),
    '5': digitPusher(5),
    '6': digitPusher(6),
    '7': digitPusher(7),
    '8': digitPusher(8),
    '9': digitPusher(9),
    '+': binaryOperator((function(o1, o2) {
      return o1 + o2;
    }), '+', function(o1, o2) {
      return "" + o1 + " + " + o2;
    }),
    '-': binaryOperator((function(o1, o2) {
      return o1 - o2;
    }), '-', function(o1, o2) {
      return "" + o1 + " - " + o2;
    }),
    '*': binaryOperator((function(o1, o2) {
      return o1 * o2;
    }), '*', function(o1, o2) {
      return "" + o1 + " * " + o2;
    }),
    '/': binaryOperator((function(o1, o2) {
      return Math.floor(o1 / o2);
    }), '/', function(o1, o2) {
      return "Math.floor(" + o1 + " / " + o2 + ")";
    }),
    '%': binaryOperator((function(o1, o2) {
      return o1 % o2;
    }), '%', function(o1, o2) {
      return "" + o1 + " % " + o2;
    }),
    '!': function(x, y, dir, index, stack) {
      if (stack.length) {
        stack.push(+(!stack.pop()));
        return '/* ! */';
      } else {
        return '/* ! */  runtime.push(+!runtime.pop())';
      }
    },
    '`': binaryOperator((function(o1, o2) {
      return +(o1 > o2);
    }), '`', function(o1, o2) {
      return "+(" + o1 + " > " + o2 + ")";
    }),
    '^': function() {
      return '/* ^ */';
    },
    '<': function() {
      return '/* < */';
    },
    'v': function() {
      return '/* v */';
    },
    '>': function() {
      return '/* > */';
    },
    '?': function() {
      return '/* ? */  return;';
    },
    '_': function() {
      return '/* _ */  return;';
    },
    '|': function() {
      return '/* | */  return;';
    },
    '"': function() {
      return '/* " */';
    },
    ':': function(x, y, dir, index, stack) {
      if (stack.length) {
        stack.push(stack[stack.length - 1]);
        return '/* : */';
      } else {
        return '/* : */  runtime.duplicate()';
      }
    },
    '\\': function(x, y, dir, index, stack) {
      var e1, e2;
      if (stack.length > 1) {
        e1 = stack[stack.length - 1];
        e2 = stack[stack.length - 2];
        stack[stack.length - 1] = e2;
        stack[stack.length - 2] = e1;
        return '/* \\ */';
      } else {
        return '/* \\ */  runtime.swap()';
      }
    },
    '$': function(x, y, dir, index, stack) {
      if (stack.length) {
        stack.pop();
        return '/* $ */';
      } else {
        return '/* $ */  runtime.pop()';
      }
    },
    '.': function(x, y, dir, index, stack) {
      if (stack.length) {
        return "/* . */  runtime.out(" + (stack.pop()) + ")";
      } else {
        return '/* . */  runtime.out(runtime.pop())';
      }
    },
    ',': function(x, y, dir, index, stack) {
      var char;
      if (stack.length) {
        char = String.fromCharCode(stack.pop());
        if (char === "'") {
          char = "\\'";
        } else if (char === '\\') {
          char = '\\\\';
        }
        return "/* , */  runtime.out('" + char + "')";
      } else {
        return '/* , */  runtime.out(String.fromCharCode(runtime.pop()))';
      }
    },
    '#': function() {
      return '/* # */';
    },
    'p': function(x, y, dir, index, stack) {
      var operand1, operand2, operand3;
      operand1 = stack.length ? stack.pop() : 'runtime.pop()';
      operand2 = stack.length ? stack.pop() : 'runtime.pop()';
      operand3 = stack.length ? stack.pop() : 'runtime.pop()';
      return ("/* p */  runtime.put(" + operand1 + ", " + operand2 + ", " + operand3 + ", " + x + ", " + y + ", '" + dir + "', " + index + ")\n") + "if (runtime.flags.pathInvalidatedAhead) {" + ("" + (stack.length ? "runtime.push(" + (stack.join(', ')) + ");" : '')) + " return; }";
    },
    'g': function(x, y, dir, index, stack) {
      var operand1, operand2;
      operand1 = stack.length ? stack.pop() : 'runtime.pop()';
      operand2 = stack.length ? stack.pop() : 'runtime.pop()';
      return "/* g */  runtime.push(runtime.get(" + operand1 + ", " + operand2 + "))";
    },
    '&': function() {
      return '/* & */  runtime.push(runtime.next())';
    },
    '~': function() {
      return '/* ~ */  runtime.push(runtime.nextChar())';
    },
    '@': function() {
      return '/* @ */  return;';
    }
  };

  OptimizinsCompiler = function() {};

  OptimizinsCompiler.assemble = function(path) {
    var charList, lines, stack;
    charList = path.getAsList();
    stack = [];
    lines = charList.map(function(entry, i) {
      var codeGenerator, ret;
      if (entry.string) {
        stack.push(entry.char.charCodeAt(0));
        return "/* '" + entry.char + "' */";
      } else {
        codeGenerator = codeMap[entry.char];
        if (codeGenerator != null) {
          ret = '';
          if (entry.char === '&' || entry.char === '~') {
            if (stack.length) {
              ret += "runtime.push(" + (stack.join(', ')) + ");\n";
            }
            stack = [];
          }
          ret += codeGenerator(entry.x, entry.y, entry.dir, i, stack);
          return ret;
        } else {
          return "/* __ " + entry.char + " */";
        }
      }
    });
    if (stack.length) {
      lines.push("runtime.push(" + (stack.join(', ')) + ")");
    }
    return lines.join('\n');
  };

  OptimizinsCompiler.compile = function(path) {
    var code, compiled;
    code = OptimizinsCompiler.assemble(path);
    path.code = code;
    compiled = new Function('runtime', code);
    return path.body = compiled;
  };

  if (window.bef == null) {
    window.bef = {};
  }

  window.bef.OptimizinsCompiler = OptimizinsCompiler;

}).call(this);
