// Generated by CoffeeScript 1.12.7
(function() {
  'use strict';
  var PathFinder, S, findPath;

  S = bef.Symbols;

  findPath = function(playfield, start) {
    var charCode, initialPath, loopingPath, path, pointer, splitPosition;
    path = new bef.Path();
    pointer = start.clone();
    while (true) {
      charCode = playfield.getAt(pointer.x, pointer.y);
      if (charCode === S.QUOT) {
        path.push(pointer.x, pointer.y, pointer.dir, charCode);
        while (true) {
          pointer.advance();
          charCode = playfield.getAt(pointer.x, pointer.y);
          if (charCode === S.QUOT) {
            path.push(pointer.x, pointer.y, pointer.dir, charCode);
            break;
          }
          path.push(pointer.x, pointer.y, pointer.dir, charCode, true);
        }
        pointer.advance();
        continue;
      }
      pointer.turn(charCode);
      if (path.hasNonString(pointer.x, pointer.y, pointer.dir)) {
        splitPosition = (path.getEntryAt(pointer.x, pointer.y, pointer.dir)).index;
        if (splitPosition > 0) {
          initialPath = path.prefix(splitPosition);
          loopingPath = path.suffix(splitPosition);
          loopingPath.looping = true;
          return {
            type: 'composed',
            initialPath: initialPath,
            loopingPath: loopingPath
          };
        } else {
          path.looping = true;
          return {
            type: 'looping',
            loopingPath: path
          };
        }
      }
      path.push(pointer.x, pointer.y, pointer.dir, charCode);
      if (charCode === S.IFV || charCode === S.IFH || charCode === S.RAND || charCode === S.END || charCode === S.PUT) {
        path.ending = {
          x: pointer.x,
          y: pointer.y,
          dir: pointer.dir,
          charCode: charCode
        };
        return {
          type: 'simple',
          path: path
        };
      }
      if (charCode === S.JUMP) {
        pointer.advance();
      }
      pointer.advance();
    }
  };

  PathFinder = function() {};

  Object.assign(PathFinder, {
    findPath: findPath
  });

  if (window.bef == null) {
    window.bef = {};
  }

  window.bef.PathFinder = PathFinder;

}).call(this);
