// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var PathSet, getHash;

  getHash = function(x, y, dir) {
    return "" + x + "_" + y + "_" + dir;
  };

  PathSet = function() {
    this.map = new Map;
  };

  PathSet.prototype.add = function(path) {
    var hash, head;
    head = path.list[0];
    hash = getHash(head.x, head.y, head.dir);
    this.map.set(hash, path);
    return this;
  };

  PathSet.prototype.has = function(x, y, dir) {
    var hash;
    hash = getHash(x, y, dir);
    return this.map.has(hash);
  };

  PathSet.prototype.getStartingFrom = function(x, y, dir) {
    var hash;
    hash = getHash(x, y, dir);
    return this.map.get(hash);
  };

  PathSet.prototype.remove = function(path) {
    var hash, head;
    head = path.list[0];
    hash = getHash(head.x, head.y, head.dir);
    this.map["delete"](hash);
    return this;
  };

  PathSet.prototype.clear = function() {
    this.map.clear();
    return this;
  };

  if (window.bef == null) {
    window.bef = {};
  }

  window.bef.PathSet = PathSet;

}).call(this);
