// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var ProgramState;

  ProgramState = function(interpreter) {
    this.interpreter = interpreter;
    this.stack = [];
    this.flags = {
      pathInvalidatedAhead: false
    };
    this.inputPointer = 0;
    this.inputList = [];
    this.outRecord = [];
  };

  ProgramState.prototype.push = function() {
    return this.stack.push.apply(this.stack, arguments);
  };

  ProgramState.prototype.pop = function() {
    if (this.stack.length < 1) {
      return 0;
    }
    return this.stack.pop();
  };

  ProgramState.prototype.out = function(e) {
    return this.outRecord.push(e);
  };

  ProgramState.prototype.setInput = function(values) {
    this.inputList = values.slice(0);
    return this.inputPointer = 0;
  };

  ProgramState.prototype.next = function() {
    var ret;
    ret = this.inputList[this.inputPointer];
    if (this.inputPointer < this.inputList.length) {
      this.inputPointer++;
      return ret;
    } else {
      return 0;
    }
  };

  ProgramState.prototype.nextChar = function() {
    var ret;
    ret = this.inputList[this.inputPointer].charCodeAt(0);
    if (this.inputPointer < this.inputList.length) {
      this.inputPointer++;
      return ret;
    } else {
      return 0;
    }
  };

  ProgramState.prototype.put = function(e, y, x, currentX, currentY, currentDir, index) {
    return this.interpreter.put(x, y, String.fromCharCode(e), currentX, currentY, currentDir, index);
  };

  ProgramState.prototype.get = function(y, x) {
    return this.interpreter.get(x, y);
  };

  ProgramState.prototype.duplicate = function() {
    var e;
    if (this.stack.length < 1) {
      return;
    }
    e = this.stack[this.stack.length - 1];
    this.stack.push(e);
  };

  ProgramState.prototype.swap = function() {
    var e1, e2;
    if (this.stack.length < 2) {
      return;
    }
    e1 = this.stack[this.stack.length - 1];
    e2 = this.stack[this.stack.length - 2];
    this.stack[this.stack.length - 1] = e2;
    this.stack[this.stack.length - 2] = e1;
  };

  ProgramState.prototype.randInt = function(max) {
    return Math.floor(Math.random() * max);
  };

  ProgramState.prototype.exit = function() {
    return this.flags.exitRequest = true;
  };

  if (window.bef == null) {
    window.bef = {};
  }

  window.bef.ProgramState = ProgramState;

}).call(this);
